name: Automated Release

on:
  push:
    branches: [test-tag]
    # paths:
    #     - "pom.xml"


jobs:
  release:
    name: Tag + Build + Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Extract version from pom.xml
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Tag version: v$VERSION"

      - name: Build JAR
        run: mvn clean package

      - name: Create Git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Create GitHub Release and Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            Automated release for version v${{ env.VERSION }}.
            Built with Maven and deployed via GitHub Actions.
          files: target/*.jar
